FROM iansmith/musl-go
MAINTAINER iansmith@igneous.io
EXPORT GOROOT=/tools/go

#useful for most situations but must be coordinated with the Pickett.jso
EXPORT GOPATH=/sample2:/vendor
export PATH=$PATH:$GOROOT/bin:/src/bin:/vendor/bin
